### Add ingredient
POST http://localhost:3001/ingredients
content-type: application/json

{
    "name": "milk",
    "category": "dairy"
}

### Get all ingredients
http://localhost:3001/ingredients/

### Delete ingredient
POST http://localhost:3001/ingredients/:id
content-type: application/json

{
    "id": "4b0fdf81-68ac-4106-983c-53502ea5a265"
}

### Get All Recipes and Their Ingredients
http://localhost:3001/recipes/

### Add recipe
POST http://localhost:3001/recipes/
content-type: application/json

{
    "name": "Mac n Cheese",
    "steps": [
        "boil pasta",
        "make cheese sauce",
        "mix"
    ],
    "ingredients": [
			{
				"id": "010d22aa-8129-43e7-941d-4a0ecb9ad68b",
				"quantity": "2",
				"unitOfMeasure": "dash"
			},
			{
				"id": "724dd25e-5d9c-4279-8eaf-c39a0ffd5362",
				"quantity": "50",
				"unitOfMeasure": "g"
			},
    ]
}

### Get all users
http://localhost:3001/users/

### Post request to authenticate user
POST http://localhost:3001/users/authenticate
content-type: application/json

{
	"username": "brando",
	"password": "IGotBumped"
}

### Get all measurements
http://localhost:3001/ingredients/measurements/
content-type: application/json